// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW0x5Dh3J-trNeQ3DdrlNwvAvM64fs85I',
    appId: '1:1084499599994:web:ce5ab868a8f364403c11c3',
    messagingSenderId: '1084499599994',
    projectId: 'potion-mixup',
    authDomain: 'potion-mixup.firebaseapp.com',
    storageBucket: 'potion-mixup.firebasestorage.app',
    measurementId: 'G-E1DCPZYNS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzTXkhqrPonBxDJSWQ_wMgEJNUI4IczPk',
    appId: '1:1084499599994:android:fa4762e593be07103c11c3',
    messagingSenderId: '1084499599994',
    projectId: 'potion-mixup',
    storageBucket: 'potion-mixup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9NxgxpozbVwiUWYZgwOI-R0U_meO1lTo',
    appId: '1:1084499599994:ios:0f9d4dbabcf714053c11c3',
    messagingSenderId: '1084499599994',
    projectId: 'potion-mixup',
    storageBucket: 'potion-mixup.firebasestorage.app',
    iosBundleId: 'com.example.potionMixup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9NxgxpozbVwiUWYZgwOI-R0U_meO1lTo',
    appId: '1:1084499599994:ios:0f9d4dbabcf714053c11c3',
    messagingSenderId: '1084499599994',
    projectId: 'potion-mixup',
    storageBucket: 'potion-mixup.firebasestorage.app',
    iosBundleId: 'com.example.potionMixup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW0x5Dh3J-trNeQ3DdrlNwvAvM64fs85I',
    appId: '1:1084499599994:web:4e0dc36bc8fadb523c11c3',
    messagingSenderId: '1084499599994',
    projectId: 'potion-mixup',
    authDomain: 'potion-mixup.firebaseapp.com',
    storageBucket: 'potion-mixup.firebasestorage.app',
    measurementId: 'G-FDJYQ2FXTF',
  );
}
